# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  stockexchangewebapi:
    image: stockexchangewebapi
    build:
      context: .
      dockerfile: StockExchange.WebAPI/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 80:80
      - 443:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
